### ISSUE TITLE
go get -u github.com/asticode/go-asticoqui/... errors

### ISSUE THREAD

**Issue by vinniyo** [asticode/go-asticoqui#6]
Trying to install on raspberry pi. Has anyone sucessfully installed on a PI? Maybe there's not enough memory. 

go/src/github.com/asticode/go-asticoqui/coqui.go:125:11: type [1073741824]TokenMetadata larger than address space
go/src/github.com/asticode/go-asticoqui/coqui.go:125:11: type [1073741824]TokenMetadata too large
go/src/github.com/asticode/go-asticoqui/coqui.go:145:11: type [1073741824]CandidateTranscript larger than address space
go/src/github.com/asticode/go-asticoqui/coqui.go:145:11: type [1073741824]CandidateTranscript too large

**Comment by Nimesh-Srivastava** [comment]
Same error here. I have 4.2 GB available on RPi 4 but this file just does not download. Haven't found a solution as of now.

**Comment by asticode** [comment]
Could you try adding `@address-too-large` at the end of your `go get` command (it should be right after the name of the repo without any space in between) and tell me whether it works better ?

**Comment by Nimesh-Srivastava** [comment]
> Could you try adding `@address-too-large` at the end of your `go get` command (it should be right after the name of the repo without any space in between) and tell me whether it works better ?

This does seem to resolve the issue, although I had to change `go get` as well as `go install` commands.

Thanks ✌🏼

**Comment by asticode** [comment]
FYI I've merged the fix in master therefore you should `go get` without `@` now 👍
